### ISSUE TITLE
Data preprocessing 

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [dragonlong/articulated-pose#13]
Hi, thanks for sharing your interesting work. I tried to run the data preprocessing code below:
```bash
python preprocess_data.py --dataset='shape2motion' --item='eyeglasses' 
```
The output shows:
```bash
dataset='shape2motion' --item='eyeglasses' 
We have 43 different instances
done for 0041 /home/user/Documents/Code/articulated-pose/dataset/shape2motion/render/eyeglasses/0041/23
done for 0041 /home/user/Documents/Code/articulated-pose/dataset/shape2motion/render/eyeglasses/0041/25
...
done for 0041 /home/user/Documents/Code/articulated-pose/dataset/shape2motion/render/eyeglasses/0041/19
We have 0 different instances []
['0007', '0016', '0036']
train_list: 
 0
test list: 
 0
``` 
It seems nothing has been done after running the data preprocessing code. I checked with the code and found the following code was commented:
```python
    # 1. collect filenames into all.txt
    collect_file(root_dset, [item], mode=args.mode)
    # PoseData     = PoseDataset(root_dset, item, is_debug=args.debug, mode=args.mode, selected_list=selected_list)
    # print('number of images: ', len(PoseData.list_rgb))

    # # 2. preprocess and save
    # for i in range(0, len(PoseData.list_rgb)):
    #     data = PoseData.__preprocess_and_save__(i)

    # 3. split data into train & test
    split_dataset(root_dset, [item], args, test_ins=infos.datasets[item].test_list, spec_ins=infos.datasets[item].spec_list, train_ins=infos.datasets[item].train_list)
```
I have tried to uncomment the code like this:
```python 
    # 1. collect filenames into all.txt
    collect_file(root_dset, [item], mode=args.mode)
    PoseData     = PoseDataset(root_dset, item, is_debug=args.debug, mode=args.mode, selected_list=selected_list)
    print('number of images: ', len(PoseData.list_rgb))

    # 2. preprocess and save
    for i in range(0, len(PoseData.list_rgb)):
        data = PoseData.__preprocess_and_save__(i)

    # 3. split data into train & test
    split_dataset(root_dset, [item], args, test_ins=infos.datasets[item].test_list, spec_ins=infos.datasets[item].spec_list, train_ins=infos.datasets[item].train_list)
```
But the code shows the following error:
```bash
...
/home/user/Documents/Code/articulated-pose/dataset/shape2motion/render/eyeglasses/0043
Object eyeglasses instance 0043 buffer loaded
number of images:  39990
current image:  /home/user/Documents/Code/articulated-pose/dataset/shape2motion/render/eyeglasses/0001/11/rgb/000000.png
Traceback (most recent call last):
  File "preprocess_data.py", line 392, in <module>
    data = PoseData.__preprocess_and_save__(i)
  File "preprocess_data.py", line 275, in __preprocess_and_save__
    projected_map = np.stack([u_map * w_channel, v_map * w_channel, depth, w_channel]).transpose([1, 2, 0])
ValueError: operands could not be broadcast together with shapes (512,512) (262144,) 
```
There are some questions I want to confirm:
1. Did I uncommented the code in the right way? Or they should not be uncommented? If they should not be uncommented, could you tell me how can I make the data pre-processing code work? 
2. Dose the `ValueError: operands could not be broadcast together with shapes (512,512) (262144,) ` happens in your environment?
Thanks!

**Comment by dragonlong** [comment]
Hi Linfang, 

I apologize for my delayed reply. To answer your first question, yes, they should be uncommented to perform the actual preprocessing; I didn't have this ValueError, all variables in [line 275](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/tools/preprocess_data.py#L275) should be array of 512 * 512, if not, the wrong one should be reshaped back. 

Best,
Xiaolong

**Comment by Lynne-Zheng-Linfang** [comment]
> Hi Linfang,
> 
> I apologize for my delayed reply. To answer your first question, yes, they should be uncommented to perform the actual preprocessing; I didn't have this ValueError, all variables in [line 275](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/tools/preprocess_data.py#L275) should be array of 512 * 512, if not, the wrong one should be reshaped back.
> 
> Best,
> Xiaolong

Thank you. The code is working now.
