### ISSUE TITLE
Why there is no matching distribution found for correlation-cuda==0.0.0

### ISSUE THREAD

**Issue by Jianghanxiao** [dragonlong/articulated-pose#15]
Hi, I try installing the environment. However, I find that there is no matching distribution found for correlation-cuda==0.0.0. Is there some way to solve this?

**Comment by KunalMGupta** [comment]
Is there any solution for this problem?

**Comment by Jianghanxiao** [comment]
Just comment this package. This is not useful in this project. The requirement.txt includes some unuseful requirements
