### ISSUE TITLE
Question about the drawer rendering pipeline

### ISSUE THREAD

**Issue by Jianghanxiao** [dragonlong/articulated-pose#16]
Hi, 

I find the current readme is for the shape2motion dataset mainly and the codes actually have contained some stuff for other datasets. I'm interested in the drawer category. Could you give some hint on the pipeline to render and process the drawer category? Which part of the codes may involve some modififying?

Thanks a lot for your help

**Comment by Jianghanxiao** [comment]
By the way, the RGB image are not saved correctly using cv2, it should invert the R and B channel. In addition, using the latest pybullet (3.0.8) can load the objs in SAPIEN with the correct texture

**Comment by dragonlong** [comment]
The drawer category is from Sapien, the rendering pipeline should be almost the same except it adds a virtual base link. cv2 saving is a known issue.
