### ISSUE TITLE
How to deal with the base part for sapien model in the preprocessing?

### ISSUE THREAD

**Issue by Jianghanxiao** [dragonlong/articulated-pose#17]
Hi,

I find that in the preprocess.py. The PoseData is written for shape2motion data. The init() can be easily modified using the get_URDF_mobility function. However, in the __preprocess_and_save__ function, I'm kind of confused about virtual link in sapien ('base' link). It will judge if there is no poing cloud for this part, then the image will just be skipped.

But I find that in other codes, the sapien dataset has been considered. So what should I modify for the PoseData. Or where do you deal with the virtual link in URDF of sapien.

Thanks a lot if you can take time to reply

**Comment by dragonlong** [comment]
Hi Jianghan, 

Thanks for your interest in this repo, regarding the virtual base link in Sapien URDF, I believe it is simply used for adding additional transformation. Pybullet will assign label '0' to this virtual link when generating the per-link mask, so any mask label >=1 corresponds to a valid link. You could fix this in `preprocess_and_save` by turning this behaviour back to the original Shape2Motion case. 

One way is to modify the code to 'ignore' the virtual base link: 1. add `num_parts = num_parts -1` after [line 187](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/tools/preprocess_data.py#L187); 2. [line 262](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/tools/preprocess_data.py#L262) to be `label[:, :]==(n+1)`. There might be other lines you need to modify accordingly, the debugging visualizations in line 352 would help. 

Best,
Xiaolong

**Comment by Jianghanxiao** [comment]
Hi Xiaolong, 

Thanks a lot for your reply!! I will have a try!!

Best,
Hanxiao(Shawn)
