### ISSUE TITLE
The file structure in ./results folder

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [dragonlong/articulated-pose#18]
Hi Xiaolong,

I am trying to run the evaluation code. However, many errors reported about the file paths in the `./results` folder, which I guess, can be well solved by knowing the file structure. Could you please specify the file structure under `./results/` (folder name, file name, file type etc.)? Especially which kind of file should be put into `./results/test_pred/3.9` and `./results/test_pred/3.91`.  I have downloaded the pre-trained module and put them into `./results/model` as the instruction. The following are the details of part of the problems:

### Error 1. 

```bash
(articulated-pose) user@lambda-dual:~/Documents/Code/articulated-pose/evaluation$ python compute_gt_pose.py --item='eyeglasses' --domain='unseen' --nocs='ANCSH' --save
Traceback (most recent call last):
  File "compute_gt_pose.py", line 43, in <module>
    all_test_h5     = os.listdir(test_h5_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/Code/articulated-pose/results/test_pred/3.9'
```
I have checked with the code, it seems that all .h5 files in `./dataset/shape2motion/hdf5/eyeglasses` should be put into `/results/test_pred/3.9` with their name changed to `instanceID_artID_frameOrder.h5`. For example, the file `/./dataset/shape2motion/hdf5/eyeglasses/0001/0/0.h5` should be moved and renamed to './results/test_pred/3.9/0001_0_0.h5'. Could you confirm this?

### Error 2.
```bash
(articulated-pose) user@lambda-dual:~/Documents/Code/articulated-pose/evaluation$ python baseline_npcs.py --item='eyeglasses' --domain='unseen' 
saving to  /home/user/Documents/Code/articulated-pose/results/test_pred/pickle3.9/unseen_ANCSH_eyeglasses_rt_pn.pkl
Traceback (most recent call last):
  File "baseline_npcs.py", line 269, in <module>
    with open(file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/Code/articulated-pose/results/test_pred/pickle3.9/unseen_ANCSH_eyeglasses_rt_pn.pkl'

```
Could you please confirm the path should be `./results/test_pred/pickle3.9/unseen_ANCSH_eyeglasses_rt_pn.pkl` instead of `/results/test_pred/pickle/3.9/unseen_ANCSH_eyeglasses_rt_pn.pkl`?

I tried to create the `pickle3.9` folder, and re-run the code:
```bash
(articulated-pose) user@lambda-dual:~/Documents/Code/articulated-pose/evaluation$ python baseline_npcs.py --item='eyeglasses' --domain='unseen' 
saving to  /home/user/Documents/Code/articulated-pose/results/test_pred/pickle3.9/unseen_ANCSH_eyeglasses_rt_pn.pkl
baseline_npcs.py:273: RuntimeWarning: Mean of empty slice.
  print('mean rotation err of part {}: \n'.format(j), 'baseline: {}'.format(np.array(r_raw_err['baseline'][j]).mean()))
/home/user/anaconda3/envs/articulated-pose/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mean rotation err of part 0: 
 baseline: nan
baseline_npcs.py:274: RuntimeWarning: Mean of empty slice.
  print('mean translation err of part {}: \n'.format(j), 'baseline: {}'.format(np.array(t_raw_err['baseline'][j]).mean()))
mean translation err of part 0: 
 baseline: nan
mean rotation err of part 1: 
 baseline: nan
mean translation err of part 1: 
 baseline: nan
mean rotation err of part 2: 
 baseline: nan
mean translation err of part 2: 
 baseline: nan
```

**Comment by dragonlong** [comment]
Hi, 

For error 1, yes, after running the step 1. predictions, [save_batch_nn](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/lib/prediction_io.py#L65) function will save the predictions into instanceID_artID_frameOrder.h5. 

For error 2, since I created a folder called 'pickle' to store all final pose estimation results per category/experiment, pickle/3.9 is the way I do. The `baseline_npcs.py` will take all networks predictions from *.h5 and estimate the pose based only on NPCS and input point clouds, then save the results into 'unseen_npcs_eyeglasses_rt_pn.pkl'. So you need to first make sure you have all the predictions from step 1. predictions. Also better to pass '--nocs=npcs' when you run this code. 

Best,
Xiaolong

**Comment by Lynne-Zheng-Linfang** [comment]
> Hi,
> 
> For error 1, yes, after running the step 1. predictions, [save_batch_nn](https://github.com/dragonlong/articulated-pose/blob/6792ae2bf139ae68091ace901bd4a8519e7111fc/lib/prediction_io.py#L65) function will save the predictions into instanceID_artID_frameOrder.h5.
> 
> For error 2, since I created a folder called 'pickle' to store all final pose estimation results per category/experiment, pickle/3.9 is the way I do. The `baseline_npcs.py` will take all networks predictions from *.h5 and estimate the pose based only on NPCS and input point clouds, then save the results into 'unseen_npcs_eyeglasses_rt_pn.pkl'. So you need to first make sure you have all the predictions from step 1. predictions. Also better to pass '--nocs=npcs' when you run this code.
> 
> Best,
> Xiaolong

Hi Xiaolong,

Thanks for replying. I just finished the step 1. The following are some errors I have encountered and the solutions I used. I share the information which might be useful for other people to run the code and for you to adjust the instruction in `README.md` document:

### 1. Directly run train.py in test mode is not working
```bash
(articulated-pose) user@lambda-dual:~/Documents/Code/articulated-pose$ python train.py --item='eyeglasses' --nocs_type='ancsh' --test
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    assert not is_testing
AssertionError
```
The error occurs because the code is trying to find the checkpoint files in `.results/model/3.9`. However, users that following the instruction to download the pre-trained models and put them to `.results/model` will turn out to have the file structure like  `.results/model/eyeglasses/3.9` etc. The way I used to solve this is to modify the `in_model_dir` and `out_model_dir` in `network_config.yml` to `results/model/eyeglasses`. 

### 2. Absolute path error.

```bash
(articulated-pose) user@lambda-dual:~/Documents/Code/articulated-pose$ python train.py --item='eyeglasses' --nocs_type='ancsh' --test
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    tf.train.Saver().restore(sess, checkpoint_path)
  File "/home/user/anaconda3/envs/articulated-pose/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1536, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/home/user/anaconda3/envs/articulated-pose/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 364, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/user/anaconda3/envs/articulated-pose/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "/home/user/anaconda3/envs/articulated-pose/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /work/cascades/lxiaol9/6DPOSE/results/model/3.9; No such file or directory
```
The solution to this is to modify the `model_checkpoint_path` in each `checkpoint.txt` file under each pre-trained model folder.

 Thanks again!
