### ISSUE TITLE
Could you offer the render parameters for drawer category in the paper?

### ISSUE THREAD

**Issue by Jianghanxiao** [dragonlong/articulated-pose#22]
Hi, I notice that in the codes, if one part is missing in the image, then the image will not be valid and the program will stop. So how do you deal with the rendering parameters to make sure that all parts of an object appear in the rendered image. Could you offer the render parameters for drawer category used in the paper? 

I mean some parameters like below stuffs.
--num=30 --cnt=31 --pitch="-90,5" --roll="-10,10" --yaw="-180,180" --min_angles="0,0" --max_angles="90,90"

Thanks a lot!!

**Comment by dragonlong** [comment]
Hi Jianghan, 

Thanks for asking. You might need to do a simple math by computing the closest distance to capture the object's full tight bounding box in the picture under certain translations. I found this one 'python render_synthetic_for_coords_drawer.py --item='4_parts' --num=30 --cnt=40 --pitch="-60,5" --yaw="-150, -30" --dis=2.5' in my old script, but not guarantee it would work. 

Best,
Xiaolong

**Comment by Jianghanxiao** [comment]
Thanks a lot, Xiaolong!!
