### ISSUE TITLE
does this rep work for sapien dataset?

### ISSUE THREAD

**Issue by liuliu66** [dragonlong/articulated-pose#3]
I found the dataset could be set to sapien with category 'drawer', but the code cannot run well. So is this rep for sapien dataset still in progress?

**Comment by dragonlong** [comment]
Currently this data loading is mainly designed for Shape2Motion dataset, but it contains the original code I use for drawer category from Sapien. It should be possible to extend to other categories with small modification(i.e, part number, path). If you could provide more specific issues when running the code, maybe I could better help you.

**Comment by liuliu66** [comment]
@dragonlong Thanks for your reply. So what should I run the code for drawer category from Sapien? I revise the urdf_modify.py file to generate syn_pX file and then render and preprocess them using get_urdf_mobility function instead of get_urdf api. Is my running correct? If possible, please provide the running tutorial and I will extend it. Thank you!

**Comment by dragonlong** [comment]
Yeah, you are doing the right thing. 'get_urdf_mobility' will only parse canonical parameters for further usage, the preprocess_data.py will get depth point cloud together with corresponding canonical coordinates, and save them into .h5 file. After that, you could use the 'create_unit_data_from_hdf5' function in dataset.py to finish ANCSH normalization pipeline.

**Comment by liuliu66** [comment]
@dragonlong Thanks for your reply. the code seems running well on sapien. I have only one further question: how do you deal with the link named 'base' and joint with type 'fixed' when processing sapien dataset? It seems that 'base' link and 'fixed' joint do not work when rendering images. So you delete them when running urdf_modify.py or just keep it during rendering because a empty link might cause the full-zero mask when segmentation training. Thank you!

**Comment by dragonlong** [comment]
If I understand your question correctly, you are wondering how to deal with empty base link in Pybullet rendering. Since we separate the whole URDF into multiple files, the empty link shouldn't be a problem. However, we need to take care of corresponding mask values for a certain link since the empty link might add 1 to later links in the kinematic chain.
