### ISSUE TITLE
About the input

### ISSUE THREAD

**Issue by DC1991** [dragonlong/articulated-pose#33]
Thanks for your work. 
In Figure 8 of the paper, I see the input is only the object point cloud and you did not mention how you segment the object points from the background.  Therefore, my question is does the network take the pre-segmented object point cloud as input?

**Comment by dragonlong** [comment]
Yes, here we actually assume we already have the pre-segmented point clouds; for preprocessing, we use the GT pose to overlay the CAD models on top of the images, so we could get GT masks, even though that won’t be perfect.

**Comment by DC1991** [comment]
I see, thanks
