### ISSUE TITLE
no function named 'solver_ransac_nonlinear'

### ISSUE THREAD

**Issue by liuliu66** [dragonlong/articulated-pose#4]
when I run the evaluation script, there is an error 'ImportError: cannot import name 'solver_ransac_nonlinear''. It seems that this function is not defined or it is renamed. Could you please fix it or give a correct evaluation tutorial? I think it is hard to reproduce the result if I use the current evaluation script.

**Comment by dragonlong** [comment]
@liuliu66 Thanks for pointing that out! Yes, that's caused by the renaming of the function, in which I have just done a quick fix to that. Let me know if you have further questions on using the post-processing function.

**Comment by liuliu66** [comment]
@dragonlong Hi, sorry for interrupting you again, in the evaluation tutorial, does it miss a command that 'python compute_gt_pose.py --item='eyeglasses' --domain='unseen' --nocs='NAOCS' --save? 

when I run the code following the evaluation tutorial, I got an error that no file named 'unseen_NAOCS_eyeglasses_rt.pkl'. I guessed the file is generated by compute_gt_pose.py by setting nocs type NAOCS. so I add this command. does it missed this code?

**Comment by Lynne-Zheng-Linfang** [comment]
> @dragonlong Hi, sorry for interrupting you again, in the evaluation tutorial, does it miss a command that 'python compute_gt_pose.py --item='eyeglasses' --domain='unseen' --nocs='NAOCS' --save?
> 
> when I run the code following the evaluation tutorial, I got an error that no file named 'unseen_NAOCS_eyeglasses_rt.pkl'. I guessed the file is generated by compute_gt_pose.py by setting nocs type NAOCS. so I add this command. does it missed this code?

Hi, I have also met with the problem. I can not find the `unseen_NAOCS_eyeglasses_rt.pkl`, and I have also tried to run the following command:
```bash
python compute_gt_pose.py --item='eyeglasses' --domain='unseen' --nocs='NAOCS' --save?
```
But the output shows the following error:
```bash
Traceback (most recent call last):
  File "compute_gt_pose.py", line 43, in <module>
    all_test_h5     = os.listdir(test_h5_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/Code/articulated-pose/results/test_pred/3.9'
```
Do you have any idea for which kind of files should be in the `test_pred/3.9` folder?

I also tried to modify `/results/eyeglasses/3.9` folder to `/results/test_pred/3.9`, but it shows:
```bash
we have 0 testing data for unseen eyeglasses
takes {} seconds 1.430511474609375e-06
```
Do you have any idea for how to get the testing data for the unseen eyeglasses? I have tried to render the dataset as the instruction in the `readme.md` file, but there are other errors that appeared. Thanks a lot!

**Comment by dragonlong** [comment]
Hi Liu, 

Sorry for my late reply. Yes, the script was originally designed to check NAOCS prediction as well, but later we found NAOCS baseline prediction is weak and not quite necessary, so you could simply ignore the NAOCS evaluation by commenting the corresponding line. Also I believe the way you add the macros should be correct. 

Best,
Xiaolong
